// 下睫毛選填區塊：左右眼共用單一種類、顏色、長度與本數。
(() => {
  const style=document.createElement('style');style.textContent=`.upper-lash-section,.lower-lash-section{margin:0 0 24px;border:1px solid #e4ddd8;border-radius:15px;background:#fdfbf9;overflow:hidden}.upper-lash-header,.lower-lash-header{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:14px 16px;background:#f7f3f0;border-bottom:1px solid #e4ddd8}.upper-lash-title,.lower-lash-title{font-weight:800;font-size:18px}.upper-lash-content{padding:16px}.upper-lash-content .eyes-grid{margin:0}.upper-lash-content .eye-panel{background:#fff;border-color:#e4ddd8}.upper-lash-count-row{display:grid;grid-template-columns:120px minmax(0,220px);gap:10px;align-items:center;margin-top:14px;padding:12px;border:1px solid #e4ddd8;border-radius:12px;background:#fff}.upper-lash-count-row label{font-weight:700;font-size:14px;color:#6f625c}.upper-lash-count-row select{width:100%;min-height:40px}.lower-lash-indicator{display:none;width:max-content;margin:-20px auto 3px;padding:0;background:transparent;color:#332d2a;font-weight:700;font-size:14px;line-height:1.2;text-align:center;position:relative;z-index:2}.lower-lash-indicator.is-visible{display:block}.lower-lash-optional{margin-left:6px;color:#a16d69;font-size:13px;font-weight:700}.lower-lash-toggle-label{display:flex;align-items:center;gap:8px;cursor:pointer;font-size:14px;white-space:nowrap}.lower-lash-toggle-label input{position:absolute;opacity:0;pointer-events:none}.lower-lash-switch{position:relative;width:46px;height:26px;flex:0 0 auto;border-radius:999px;background:#cfc6c1;transition:.2s}.lower-lash-switch::after{content:"";position:absolute;top:3px;left:3px;width:20px;height:20px;border-radius:50%;background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.2);transition:.2s}.lower-lash-toggle-label input:checked+.lower-lash-switch{background:#302a27}.lower-lash-toggle-label input:checked+.lower-lash-switch::after{transform:translateX(20px)}.lower-lash-content{padding:16px}.lower-lash-fields{display:grid;grid-template-columns:minmax(120px,.7fr) minmax(160px,1fr) minmax(160px,1fr);gap:12px}.lower-lash-field{display:flex;flex-direction:column;gap:7px;padding:12px;border:1px solid #e4ddd8;border-radius:12px;background:#fff}.lower-lash-field-label{font-weight:700;font-size:14px;color:#6f625c}.lower-lash-brand-value{display:flex;align-items:center;min-height:40px;font-size:17px}.lower-lash-field select{width:100%;min-height:40px}@media(max-width:1024px){.lower-lash-indicator{margin:-30px auto 3px}}@media(max-width:767px){.upper-lash-content{padding:12px 10px}.upper-lash-count-row{grid-template-columns:1fr}.lower-lash-header{align-items:flex-start;flex-direction:column}.lower-lash-fields{grid-template-columns:1fr}.lower-lash-indicator{font-size:14px}}`;document.head.appendChild(style);
  const toggle=document.getElementById('lowerLashToggle'),content=document.getElementById('lowerLashContent'),lengthSelect=document.getElementById('lowerLashLength'),countSelect=document.getElementById('lowerLashCount'),summaryRow=document.getElementById('lowerLashSummaryRow'),summaryType=document.getElementById('lowerLashTypeSummary'),summaryColor=document.getElementById('lowerLashColorSummary'),leftEyeSvg=document.getElementById('leftEyeSvg'),rightEyeSvg=document.getElementById('rightEyeSvg');if(!toggle||!content||!lengthSelect||!countSelect)return;
  function loadLowerSettings(){try{const saved=JSON.parse(localStorage.getItem('lashRecordSettings'))||{};return{types:Array.isArray(saved.lowerLashTypes)&&saved.lowerLashTypes.length?saved.lowerLashTypes:['M'],colors:{M:['黑色','棕色'],...(saved.lowerLashColors||{})}}}catch{return{types:['M'],colors:{M:['黑色','棕色']}}}}
  const lowerSettings=loadLowerSettings();if(summaryType)summaryType.innerHTML=lowerSettings.types.map(v=>`<option value="${v}">${v}</option>`).join('');
  function renderColors(){if(!summaryColor)return;summaryColor.innerHTML='<option value="">請選擇顏色</option>';const colors=lowerSettings.colors[summaryType?.value||'M']||[];colors.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;summaryColor.appendChild(o)});summaryColor.value=''}renderColors();
  function createIndicator(eyeSvg,id){if(!eyeSvg||document.getElementById(id))return document.getElementById(id);const x=document.createElement('div');x.id=id;x.className='lower-lash-indicator';eyeSvg.insertAdjacentElement('afterend',x);return x}const leftIndicator=createIndicator(leftEyeSvg,'leftLowerLashIndicator'),rightIndicator=createIndicator(rightEyeSvg,'rightLowerLashIndicator');
  lengthSelect.innerHTML=[4,5,6,7].map(v=>`<option value="${v}">${v} mm</option>`).join('');let counts=['20','30'];try{const s=JSON.parse(localStorage.getItem('lashRecordSettings'));if(Array.isArray(s?.lowerLashCounts)&&s.lowerLashCounts.length)counts=s.lowerLashCounts.map(String)}catch{}countSelect.innerHTML=counts.map(v=>`<option value="${v}">${v} 本</option>`).join('');
  function updateIndicators(){const text=`${summaryType?.value||'M'}${lengthSelect.value}`;[leftIndicator,rightIndicator].forEach(x=>{if(x){x.textContent=text;x.classList.toggle('is-visible',toggle.checked)}})}function sync(){content.hidden=!toggle.checked;if(summaryRow)summaryRow.hidden=!toggle.checked;updateIndicators()}
  toggle.addEventListener('change',sync);lengthSelect.addEventListener('change',updateIndicators);summaryType?.addEventListener('change',()=>{renderColors();updateIndicators()});sync();
  document.getElementById('save')?.addEventListener('click',()=>{const output=document.getElementById('output');if(!output)return;try{const data=JSON.parse(output.textContent||'{}');data.lowerLash=toggle.checked?{type:summaryType?.value||'M',color:summaryColor?.value||'',length:Number(lengthSelect.value),count:countSelect.value}:null;output.textContent=JSON.stringify(data,null,2)}catch{}});
})();